ozay-postgresql:
  container_name: ozay-postgresql
  image: postgres:9.4.5
  # volumes:
  #   - ~/volumes/jhipster/ozay/postgresql/:/var/lib/postgresql/
  environment:
    - POSTGRES_USER=ozay
    - POSTGRES_PASSWORD=
  ports:
    - "5432:5432"
